version: "3"
services:
    db:
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_PASS: postgres
            POSTGRES_USER: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
            - todolist-db:/var/lib/postgresql/data
    todolist:
        container_name: todolist
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - 8181:8080
volumes:
    todolist-db:
        driver: local